/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TextCategory = IDL.Variant({
  'boundaries' : IDL.Null,
  'flirty' : IDL.Null,
  'missingYou' : IDL.Null,
  'pullAway' : IDL.Null,
  'apology' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RelationshipStatus = IDL.Variant({
  'healing' : IDL.Null,
  'married' : IDL.Null,
  'single' : IDL.Null,
  'inRelationship' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'status' : IDL.Opt(RelationshipStatus),
  'nickname' : IDL.Opt(IDL.Text),
  'isPremium' : IDL.Bool,
});
export const FavoriteMessage = IDL.Record({
  'id' : IDL.Nat,
  'message' : IDL.Text,
  'category' : TextCategory,
});
export const Entry = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'timestamp' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFavorite' : IDL.Func([TextCategory, IDL.Text], [], []),
  'addJournalEntry' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkPremiumStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'deleteFavorite' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteJournalEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllPremiumUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFavorites' : IDL.Func([], [IDL.Vec(FavoriteMessage)], ['query']),
  'getJournalEntries' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setPremiumUser' : IDL.Func([], [], []),
  'updateNickname' : IDL.Func([IDL.Text], [], []),
  'updateStatus' : IDL.Func([RelationshipStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TextCategory = IDL.Variant({
    'boundaries' : IDL.Null,
    'flirty' : IDL.Null,
    'missingYou' : IDL.Null,
    'pullAway' : IDL.Null,
    'apology' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RelationshipStatus = IDL.Variant({
    'healing' : IDL.Null,
    'married' : IDL.Null,
    'single' : IDL.Null,
    'inRelationship' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'status' : IDL.Opt(RelationshipStatus),
    'nickname' : IDL.Opt(IDL.Text),
    'isPremium' : IDL.Bool,
  });
  const FavoriteMessage = IDL.Record({
    'id' : IDL.Nat,
    'message' : IDL.Text,
    'category' : TextCategory,
  });
  const Entry = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'timestamp' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFavorite' : IDL.Func([TextCategory, IDL.Text], [], []),
    'addJournalEntry' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkPremiumStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'deleteFavorite' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteJournalEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllPremiumUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFavorites' : IDL.Func([], [IDL.Vec(FavoriteMessage)], ['query']),
    'getJournalEntries' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setPremiumUser' : IDL.Func([], [], []),
    'updateNickname' : IDL.Func([IDL.Text], [], []),
    'updateStatus' : IDL.Func([RelationshipStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };