/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Entry {
  'id' : bigint,
  'content' : string,
  'timestamp' : bigint,
}
export interface FavoriteMessage {
  'id' : bigint,
  'message' : string,
  'category' : TextCategory,
}
export type RelationshipStatus = { 'healing' : null } |
  { 'married' : null } |
  { 'single' : null } |
  { 'inRelationship' : null };
export type TextCategory = { 'boundaries' : null } |
  { 'flirty' : null } |
  { 'missingYou' : null } |
  { 'pullAway' : null } |
  { 'apology' : null };
export interface UserProfile {
  'status' : [] | [RelationshipStatus],
  'nickname' : [] | [string],
  'isPremium' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFavorite' : ActorMethod<[TextCategory, string], undefined>,
  'addJournalEntry' : ActorMethod<[string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkPremiumStatus' : ActorMethod<[], boolean>,
  'deleteFavorite' : ActorMethod<[bigint], boolean>,
  'deleteJournalEntry' : ActorMethod<[bigint], boolean>,
  'getAllPremiumUsers' : ActorMethod<[], Array<Principal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFavorites' : ActorMethod<[], Array<FavoriteMessage>>,
  'getJournalEntries' : ActorMethod<[], Array<Entry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setPremiumUser' : ActorMethod<[], undefined>,
  'updateNickname' : ActorMethod<[string], undefined>,
  'updateStatus' : ActorMethod<[RelationshipStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];