/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface FavoriteMessage {
    id: bigint;
    message: string;
    category: TextCategory;
}
export interface Entry {
    id: bigint;
    content: string;
    timestamp: bigint;
}
export interface UserProfile {
    status?: RelationshipStatus;
    nickname?: string;
    isPremium: boolean;
}
export enum RelationshipStatus {
    healing = "healing",
    married = "married",
    single = "single",
    inRelationship = "inRelationship"
}
export enum TextCategory {
    boundaries = "boundaries",
    flirty = "flirty",
    missingYou = "missingYou",
    pullAway = "pullAway",
    apology = "apology"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addFavorite(category: TextCategory, message: string): Promise<void>;
    addJournalEntry(content: string): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkPremiumStatus(): Promise<boolean>;
    deleteFavorite(favoriteId: bigint): Promise<boolean>;
    deleteJournalEntry(entryId: bigint): Promise<boolean>;
    getAllPremiumUsers(): Promise<Array<Principal>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFavorites(): Promise<Array<FavoriteMessage>>;
    getJournalEntries(): Promise<Array<Entry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setPremiumUser(): Promise<void>;
    updateNickname(nickname: string): Promise<void>;
    updateStatus(status: RelationshipStatus): Promise<void>;
}
import type { FavoriteMessage as _FavoriteMessage, RelationshipStatus as _RelationshipStatus, TextCategory as _TextCategory, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addFavorite(arg0: TextCategory, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFavorite(to_candid_TextCategory_n1(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFavorite(to_candid_TextCategory_n1(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async addJournalEntry(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addJournalEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJournalEntry(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkPremiumStatus(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkPremiumStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkPremiumStatus();
            return result;
        }
    }
    async deleteFavorite(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFavorite(arg0);
            return result;
        }
    }
    async deleteJournalEntry(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJournalEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJournalEntry(arg0);
            return result;
        }
    }
    async getAllPremiumUsers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPremiumUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPremiumUsers();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFavorites(): Promise<Array<FavoriteMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFavorites();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFavorites();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJournalEntries(): Promise<Array<Entry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJournalEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJournalEntries();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setPremiumUser(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPremiumUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPremiumUser();
            return result;
        }
    }
    async updateNickname(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNickname(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNickname(arg0);
            return result;
        }
    }
    async updateStatus(arg0: RelationshipStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStatus(to_candid_RelationshipStatus_n21(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStatus(to_candid_RelationshipStatus_n21(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_FavoriteMessage_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FavoriteMessage): FavoriteMessage {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_RelationshipStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RelationshipStatus): RelationshipStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_TextCategory_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TextCategory): TextCategory {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RelationshipStatus]): RelationshipStatus | null {
    return value.length === 0 ? null : from_candid_RelationshipStatus_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    message: string;
    category: _TextCategory;
}): {
    id: bigint;
    message: string;
    category: TextCategory;
} {
    return {
        id: value.id,
        message: value.message,
        category: from_candid_TextCategory_n17(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: [] | [_RelationshipStatus];
    nickname: [] | [string];
    isPremium: boolean;
}): {
    status?: RelationshipStatus;
    nickname?: string;
    isPremium: boolean;
} {
    return {
        status: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.status)),
        nickname: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.nickname)),
        isPremium: value.isPremium
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    healing: null;
} | {
    married: null;
} | {
    single: null;
} | {
    inRelationship: null;
}): RelationshipStatus {
    return "healing" in value ? RelationshipStatus.healing : "married" in value ? RelationshipStatus.married : "single" in value ? RelationshipStatus.single : "inRelationship" in value ? RelationshipStatus.inRelationship : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    boundaries: null;
} | {
    flirty: null;
} | {
    missingYou: null;
} | {
    pullAway: null;
} | {
    apology: null;
}): TextCategory {
    return "boundaries" in value ? TextCategory.boundaries : "flirty" in value ? TextCategory.flirty : "missingYou" in value ? TextCategory.missingYou : "pullAway" in value ? TextCategory.pullAway : "apology" in value ? TextCategory.apology : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FavoriteMessage>): Array<FavoriteMessage> {
    return value.map((x)=>from_candid_FavoriteMessage_n15(_uploadFile, _downloadFile, x));
}
function to_candid_RelationshipStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RelationshipStatus): _RelationshipStatus {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_TextCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TextCategory): _TextCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: RelationshipStatus;
    nickname?: string;
    isPremium: boolean;
}): {
    status: [] | [_RelationshipStatus];
    nickname: [] | [string];
    isPremium: boolean;
} {
    return {
        status: value.status ? candid_some(to_candid_RelationshipStatus_n21(_uploadFile, _downloadFile, value.status)) : candid_none(),
        nickname: value.nickname ? candid_some(value.nickname) : candid_none(),
        isPremium: value.isPremium
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TextCategory): {
    boundaries: null;
} | {
    flirty: null;
} | {
    missingYou: null;
} | {
    pullAway: null;
} | {
    apology: null;
} {
    return value == TextCategory.boundaries ? {
        boundaries: null
    } : value == TextCategory.flirty ? {
        flirty: null
    } : value == TextCategory.missingYou ? {
        missingYou: null
    } : value == TextCategory.pullAway ? {
        pullAway: null
    } : value == TextCategory.apology ? {
        apology: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RelationshipStatus): {
    healing: null;
} | {
    married: null;
} | {
    single: null;
} | {
    inRelationship: null;
} {
    return value == RelationshipStatus.healing ? {
        healing: null
    } : value == RelationshipStatus.married ? {
        married: null
    } : value == RelationshipStatus.single ? {
        single: null
    } : value == RelationshipStatus.inRelationship ? {
        inRelationship: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
